### ISSUE TITLE
How to make calls using Bearer token?

### ISSUE THREAD

**Issue by jankulma-turbine** [FeedHive/twitter-api-client#74]
Hi,

Thanks for great lib!

There is endpoint to obtain bearer token, however I dont see in docs / code how to use it to make requests.

Is it supported?

**Comment by SimonHoiberg** [comment]
Hi @jankulma-turbine.

Currently, this is not supported - but it's something we're planning on adding soon.
If you only need to read from the public parts of Twitter, you can simply provide the credentials you create directly from the Twitter Developer account.

Otherwise, you'll have to go through the 3-legged OAuth flow to obtain the credentials :blush: 

I'll close this issue for now, and we will address this request at a later point.
